### ISSUE TITLE
Support for Ethereum Address Verification

### ISSUE THREAD

**Issue by obstropolos** [spruceid/tzprofiles#94]
# Clarification and Motivation 

Along with social profile verifications, we should enable users to demonstrate ownership over an Ethereum address (EIP-712) and associate it with their profile. In doing so, you've now created a basic cross-chain link allowing a Tezos account to demonstrate a particular transaction history on another chain by proving that they own a particular account. From here, it can be possible to associate even deeper cross-chain credentials even at the dapp level so long as a user can prove basic ownership over an account. 

# Acceptance Criteria 
As a user: 
- I can connect my wallet to Tezos Profiles and view available credentials
- I can obtain an Ethereum Account Controller credential through Tezos Profiles by: 
   - Connecting my Ethereum wallet such as MetaMask or TrustWallet 
   - Signing an EIP-712 based challenge 
   - Verifying completion of the signature 
- I can add this Ethereum Account Controller credential to my existing smart contract if I've already deployed a profile

**Comment by krhoda** [comment]
Updates, as suggested by obstropolos:

* have 3 sections: available / pending / and my credentials depending on the state of if it has been added or not
* On the Ethereum credential, the proof is ‘Wallet Signature’
* add a small ethereum logo icon similar to the twitter page that maybe links out to the user’s etherscan
* Instead of “self-attested” should be “Signed with Ethereum wallet”
* On the page, it should look exactly like the Twitter page (Sending design)
* prompt a user to hit a button to prompt their metamask.
